import * as Cabinet from '../controller/cabinet'
export const cabinetResolver = {
    createNewCabinet: Cabinet.createNewCabinet,
    listAllCabinets: Cabinet.listAllCabinets,
    cabinetSearchTest: Cabinet.cabinetSearchTest,
    addNewPatientToCabinet: Cabinet.addNewPatientToCabinet,
    listCabinetPatients: Cabinet.listCabinetPatients,
    cabinetPatientDetails: Cabinet.cabinetPatientDetails,
    cabinetFindPatient: Cabinet.cabinetFindPatient,
    cabinetAddLabOrder: Cabinet.cabinetAddLabOrder,
    addMultipleCabinets: Cabinet.addMultipleCabinets,
    listCabinetsCities: Cabinet.listCabinetsCities,
    listCabinetsTwntyByCity: Cabinet.listCabinetsTwntyByCity,
    listCabinetsAllByCity: Cabinet.listCabinetsAllByCity,
    listCabinetDetailsById: Cabinet.listCabinetDetailsById,
    addPatientToWaitingRoom: Cabinet.addPatientToWaitingRoom,
    listWaitingPatients: Cabinet.listWaitingPatients,
    updatePatientToViewed: Cabinet.updatePatientToViewed,
    updatePatientToFinished: Cabinet.updatePatientToFinished,
    setPatientToViewed: Cabinet.setPatientToViewed,
    setPatientToFinished: Cabinet.setPatientToFinished,
    setPatientToWaiting: Cabinet.setPatientToWaiting,
    createCabinetsSiteMap: Cabinet.createCabinetsSiteMap,
};
