name: Deploy Image with Version

on:
  push:
    tags: 
      - "*" 
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo $GITHUB_REF