name : Deploy Production Application
on:
  push:
    branches:
      - "master"
jobs:
  Make_build_Application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: remove mongoose type file
        run: rm node_modules/mongoose/index.d.ts
      - name: move mogoose typing file
        run: mv mongoose/index.txt node_modules/mongoose/index.d.ts
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: khmammed/ittyni
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: dockerfileProd
          push: true
          tags: khmammed/ittyni:api_prod
          labels: ${{ steps.meta.outputs.labels }}

  update_deployment_services:
    name: deploy to kubernetes cluster
    needs : "Make_build_Application"
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo 
        uses: actions/checkout@v3
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUB_CONFIG}} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name : update ittyni production 
        run : kubectl rollout restart deployment tt-prod-api