name : Deploy Production Application
on:
  pull_request:
    branches:
      - "develop"
jobs:
  Make_build_Application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: remove mongoose type file
        run: rm node_modules/mongoose/index.d.ts
      - name: move mogoose typing file
        run: mv mongoose/index.txt node_modules/mongoose/index.d.ts
      - name: Build Application
        run: npm run tsc